### ISSUE TITLE
bundle install falla con linecache debido a incompatibilidad con Ruby 1.9

### ISSUE THREAD

**Issue by sebasmagri** [GARUMFundatio/Bazar#11]
La traza de bundle install es:

```
Bundling your gems. This may take a few minutes on first run.
Fetching git://github.com/odorcicd/authlogic.git
remote: Counting objects: 3652, done.
remote: Compressing objects: 100% (1337/1337), done.
remote: Total 3652 (delta 2389), reused 3331 (delta 2193)
Receiving objects: 100% (3652/3652), 574.45 KiB | 91 KiB/s, done.
Resolving deltas: 100% (2389/2389), done.
Fetching git://github.com/thoughtbot/paperclip.git
remote: Counting objects: 3496, done.
remote: Compressing objects: 100% (1635/1635), done.
remote: Total 3496 (delta 2329), reused 2841 (delta 1756)
Receiving objects: 100% (3496/3496), 557.74 KiB | 123 KiB/s, done.
Resolving deltas: 100% (2329/2329), done.
Fetching git://github.com/primerano/acts_as_ferret.git
remote: Counting objects: 3050, done.
remote: Compressing objects: 100% (955/955), done.
remote: Total 3050 (delta 1767), reused 3012 (delta 1752)
Receiving objects: 100% (3050/3050), 548.95 KiB | 123 KiB/s, done.
Resolving deltas: 100% (1767/1767), done.
Fetching source index for http://rubygems.org/
Installing rake (0.9.1) 
Using abstract (1.0.0) 
Using activesupport (3.0.7) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.7) 
Using erubis (2.6.6) 
Using rack (1.2.3) 
Using rack-mount (0.6.14) 
Using rack-test (0.5.7) 
Using tzinfo (0.3.27) 
Using actionpack (3.0.7) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.19) 
Using actionmailer (3.0.7) 
Using arel (2.0.10) 
Using activerecord (3.0.7) 
Using activeresource (3.0.7) 
Installing acts-as-taggable-on (2.0.6) 
Installing jk-ferret (0.11.8.3) with native extensions 
Using bundler (1.0.14) 
Using thor (0.14.6) 
Using railties (3.0.7) 
Using rails (3.0.7) 
Using acts_as_ferret (0.5.2) from git://github.com/primerano/acts_as_ferret.git (at master) 
Using authlogic (2.1.3) from git://github.com/odorcicd/authlogic.git (at rails3) 
Installing babosa (0.3.4) 
Using bazarcms (0.0.5) from source at ../bazarcms 
Installing cocaine (0.0.2) 
Installing columnize (0.3.2) 
Installing dalli (1.0.5) 
Installing dynamic_form (1.1.4) 
Installing exception_notification (2.4.0) 
Installing fastercsv (1.5.4) 
Installing friendly_id (3.2.1.1) 
Installing jquery-rails (1.0.9) 
Installing json (1.5.1) with native extensions 
Installing linecache (0.43) with native extensions /home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:533:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

        /home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/bin/ruby extconf.rb 
Can't handle 1.9.x yet
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/bin/ruby


Gem files will remain installed in /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/linecache-0.43 for inspection.
Results logged to /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/linecache-0.43/ext/gem_make.out
    from /home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:511:in `block in build_extensions'
    from /home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:486:in `each'
    from /home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:486:in `build_extensions'
    from /home/sebasmagri/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:159:in `install'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/source.rb:101:in `block in install'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/rubygems_integration.rb:78:in `preserve_paths'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/source.rb:91:in `install'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/installer.rb:58:in `block (2 levels) in run'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/rubygems_integration.rb:93:in `with_build_args'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/installer.rb:57:in `block in run'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/spec_set.rb:12:in `block in each'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/spec_set.rb:12:in `each'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/spec_set.rb:12:in `each'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/installer.rb:49:in `run'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/installer.rb:8:in `install'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/cli.rb:222:in `install'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/vendor/thor.rb:246:in `dispatch'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/lib/bundler/vendor/thor/base.rb:389:in `start'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/gems/bundler-1.0.14/bin/bundle:13:in `<top (required)>'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/bin/bundle:19:in `load'
    from /home/sebasmagri/.rvm/gems/ruby-1.9.2-p180@bazar/bin/bundle:19:in `<main>'
```

Hay soporte para Ruby 1.9? O solo se puede utilizar actualmente 1.8?

**Comment by GARUMFundatio** [comment]
ahora mismo solo soportamos 1.8.7 y recomedamos ruby enterprise

si buscas un poco en google, una vez encontre la solucin para linecache
pero no lo hemos probado todava.

Juantoms Garca
608 189 047 - 606 505 322

**Comment by sebasmagri** [comment]
Si, con ree-1.8.7 todo anda bien...

**Comment by GARUMFundatio** [comment]
revisaremos lo de 1.9 cuando este ms estable con rails 3

Juantoms Garca
608 189 047 - 606 505 322
