### ISSUE TITLE
db:migrate falla con sqlite3

### ISSUE THREAD

**Issue by sebasmagri** [GARUMFundatio/Bazar#13]
La traza del comando es:

```
$ RAILS_ENV=test rake db:migrate --trace
Bazarcms:: inicializo el engine 1 <---------------------------
WARNING: Global access to Rake DSL methods is deprecated.  Please Include
...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method Bazar::Application#task called at /home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/railties-3.0.7/lib/rails/application.rb:215:in `initialize_tasks'
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
[FALLO]
No existe el fichero de configuración!Si está haciendo la instalación inicial esto es normal
bazarcms:: inicializo el engine <---------------------
inflectors de la gema bazarcms
Inicializando el exception
bazar:: borro los inflectors
bazar:: nuevos inflectors
** Execute db:migrate
==  CreateUsers: migrating ====================================================
-- create_table(:users)
   -> 0.0026s
-- add_index(:users, ["login"], {:unique=>true, :name=>"index_users_on_login"})
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: index index_users_on_login already exists: CREATE UNIQUE INDEX "index_users_on_login" ON "users" ("login")
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract_adapter.rb:207:in `log'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/connection_adapters/sqlite_adapter.rb:135:in `execute'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:348:in `add_index'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:383:in `send'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:383:in `method_missing'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:359:in `say_with_time'
/home/sebasmagri/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/benchmark.rb:293:in `measure'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:359:in `say_with_time'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:379:in `method_missing'
/home/sebasmagri/Projects/Bazar/Bazar/db/migrate/20100923055542_create_users.rb:22:in `up_without_benchmarks'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:312:in `send'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:312:in `migrate'
/home/sebasmagri/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/benchmark.rb:293:in `measure'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:312:in `migrate'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:395:in `__send__'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:395:in `migrate'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:537:in `migrate'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:611:in `call'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:611:in `ddl_transaction'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in `transaction'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/transactions.rb:207:in `transaction'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:611:in `ddl_transaction'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:536:in `migrate'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:523:in `each'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:523:in `migrate'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:433:in `up'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/migration.rb:415:in `migrate'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/activerecord-3.0.7/lib/active_record/railties/databases.rake:142
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:205:in `call'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:205:in `execute'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:200:in `each'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:200:in `execute'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:158:in `invoke_with_call_chain'
/home/sebasmagri/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/task.rb:144:in `invoke'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:112:in `invoke_task'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:90:in `top_level'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:90:in `each'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:90:in `top_level'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:129:in `standard_exception_handling'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:84:in `top_level'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:62:in `run'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:129:in `standard_exception_handling'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/lib/rake/application.rb:59:in `run'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/gems/rake-0.9.1/bin/rake:32
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/bin/rake:19:in `load'
/home/sebasmagri/.rvm/gems/ree-1.8.7-2011.03@bazar/bin/rake:19
Tasks: TOP => db:migrate
```

La configuración de la base de datos es:

```
$ cat config/database.yml
test:
    adapter: sqlite3
    database: db/test.sqlite3
    pool: 5
    timeout: 5000
```

**Comment by GARUMFundatio** [comment]
maana preparo un dump en formato sqlite3 y te lo mando.

Juantoms Garca
608 189 047 - 606 505 322

**Comment by sebasmagri** [comment]
Excelente...
